baseURL = 'https://arthursstrong.github.io/hugo-spmnoticias/'
defaultContentLanguage = 'es'
locale = 'es-mx'
title = 'SPM Noticias'
theme = 'ananke'

[pagination]
  pagerSize = 10

[params]
  description = 'Noticias y artículos de SPM Noticias'
  show_reading_time = true

[menus]
  [[menus.main]]
    name = 'Artículos'
    pageRef = '/posts'
    weight = 10
